services:
  backend:
    build: .
    container_name: legal_ai_backend
    ports:
      - "8001:8001"
    depends_on:          # ← ADD these two
      - qdrant
      - postgres
      - redis
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - POSTGRES_HOST=postgres    # ← ADD
      - POSTGRES_DB=legal_ai      # ← ADD
      - POSTGRES_USER=postgres    # ← ADD
      - POSTGRES_PASSWORD=admin   # ← ADD
      - REDIS_HOST=redis          # ← ADD
    volumes:
      - .:/app

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant_db
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  ui:
    build: .
    container_name: legal_ai_ui
    ports:
      - "8501:8501"
    depends_on:
      - backend
    command: streamlit run ui.py --server.port=8501 --server.address=0.0.0.0
    volumes:
      - .:/app
    
    
  redis:
    image: redis:7
    container_name: legal_ai_redis
    ports:
      - "6379:6379"
  

  postgres:
    image: postgres:15
    container_name: legal_ai_postgres
    environment:
      POSTGRES_DB: legal_ai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

volumes:
  qdrant_storage: